
- name: set data directory location
  set_fact:
    vm_data: "{{ansible_env.HOME}}/.local/share/vbox-docker"

- name: create directory
  file:
    state: directory
    path: "{{vm_data}}"
  tags: provision
