
- name: create and register new vm
  command: VBoxManage createvm --name "{{vm_name}}" --ostype Ubuntu_64 --register
  register: vm_created

- name: set ram
  command: VBoxManage modifyvm "{{vm_name}}" --memory "{{vm_memory}}"

- name: set number of cpus
  command: VBoxManage modifyvm "{{vm_name}}" --cpus "{{vm_cpus}}"

- name: set boot order
  command: VBoxManage modifyvm "{{vm_name}}" --boot1 disk

- name: create network interface for private ip
  command: VBoxManage hostonlyif create
  register: hostonlyif_create

- name: extract network interface name
  set_fact:
    vm_interface: "{{hostonlyif_create.stdout | regex_search('vboxnet[0-9]+')}}"

- name: configure to use dhcp
  command: VBoxManage dhcpserver add --netname "HostInterfaceNetworking-{{vm_interface}}" --netmask 255.255.255.0 --lowerip 10.77.77.5 --upperip 10.77.77.250 --ip 10.77.77.4 --enable

- name: store network interface
  copy:
    content: "{{vm_interface}}"
    dest: "{{data_dir}}/interface"

- name: configure ssh and external networking
  command: VBoxManage modifyvm "{{vm_name}}" --nic1 nat --natpf1 "guestssh,tcp,127.0.0.1,2222,,22"

- name: add private networking adapter
  command: VBoxManage modifyvm "{{vm_name}}" --nic2 hostonly --hostonlyadapter2 "{{vm_interface}}" --cableconnected2 on

- name: create main storage controller
  command: VBoxManage storagectl "{{vm_name}}" --name main --add sata --controller IntelAhci --bootable on

- name: attach main storage
  command: VBoxManage storageattach "{{vm_name}}" --storagectl main --port 0 --device 0 --type hdd --medium "{{data_dir}}/vbox-docker.vdi"
