
- name: create and register new vm
  command: VBoxManage createvm --name "{{vm_name}}" --ostype Linux_64 --register
  register: vm_created

- name: set boot order
  command: VBoxManage modifyvm "{{vm_name}}" --boot1 disk

- name: create network interface for private ip
  command: VBoxManage hostonlyif create
  register: hostonlyif_create

- name: extract network interface name
  set_fact:
    vm_interface: "{{hostonlyif_create.stdout | regex_search('vboxnet[0-9]+')}}"

- name: configure interface
  command: VBoxManage hostonlyif ipconfig {{vm_interface}} --ip 10.77.77.77

- name: configure external networking
  command: VBoxManage modifyvm "{{vm_name}}" --nic1 nat

- name: use the host dns
  command: VBoxManage modifyvm "{{vm_name}}" --natdnsproxy1 on

- name: add private networking adapter
  command: VBoxManage modifyvm "{{vm_name}}" --nic2 hostonly --hostonlyadapter2 "{{vm_interface}}" --cableconnected2 on

- name: create main storage controller
  command: VBoxManage storagectl "{{vm_name}}" --name main --add sata --controller IntelAhci --bootable on

- name: attach main storage
  command: VBoxManage storageattach "{{vm_name}}" --storagectl main --port 0 --device 0 --type hdd --medium "{{vm_data}}/vbox-docker.vdi"
