- name: list vms
  shell: VBoxManage list vms | cut -d ' ' -f 1 | tr -d '"'
  register: vm_list
  tags: provision

- name: create vm if not present
  when: vm_name not in vm_list.stdout
  include_tasks: ./create.yml
  tags: provision

- name: list running vms
  command: VBoxManage list runningvms
  register: runningvms

- name: start virtual machine
  when: vm_name not in runningvms.stdout
  command: VBoxManage startvm "{{vm_name}}" --type headless
