
- name: check if workspace medium exists
  stat:
    path: "{{vm_data}}/workspace.vdi"
  register: workspace

- name: create vdi
  when: not workspace.stat.exists
  command: VBoxManage createmedium disk --filename "{{vm_data}}/workspace.vdi" --size "{{vm_workspace_size}}"

- name: show vm info
  command: VBoxManage showvminfo "{{vm_name}}" --machinereadable
  register: vminfo

- name: connect vdi to virtual machine
  when: |
    '"main-1-0"="none"' in vminfo.stdout
  command: VBoxManage storageattach "{{vm_name}}" --storagectl main --port 1 --device 0 --type hdd --medium "{{vm_data}}/workspace.vdi"
