- hosts: host
  roles:
  - vm_data
  - vm_image
  - vm_name
  - vm_instance
  - vm_ssh

- hosts: vm
  roles:
  - user
  - docker
  - workspace
  - nfs
  - container

- hosts: host
  roles:
  - nfs_client
