- hosts: host
  roles:
  - vm_data
  - vm_image
  - vm_name
  - vm_instance
  - vm_ssh

- hosts: vm
  roles:
  - repos
  - swap
  - user
  - guest_additions
  - docker
  - workspace
  - host_ssh
  - nfs
  - container

- hosts: host
  roles:
  - nfs_client
