- name: add parted
  apk:
    name: parted
  tags: provision

- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
  tags: provision

- name: create filesystem
  filesystem:
    fstype: ext4
    dev: /dev/sdb1
  tags: provision

- name: create workspace directory
  file:
    state: directory
    path: "/home/{{user_name}}/workspace"
  tags: provision

- name: mount workspace
  mount:
    src: /dev/sdb1
    path: "/home/{{user_name}}/workspace"
    state: mounted
    fstype: ext4
  register: workspace_mount
  tags: provision

- name: set permissions
  file:
    path: "/home/{{user_name}}/workspace"
    group: "{{user_group_name}}"
    owner: "{{user_name}}"
  when: workspace_mount.changed
  tags: provision
