- name: check if name is set
  stat:
    path: "{{data_dir}}/name"
  register: vm_name_stat
  tags: provision

- name: set name
  when: not vm_name_stat.stat.exists
  include_tasks: ./set_name.yml
  tags: provision

- name: load vm name
  slurp:
    src: "{{data_dir}}/name"
  register: vm_name_file

- name: set vm name 
  set_fact:
    vm_name: "{{vm_name_file['content'] | b64decode}}"
