
- name: find python shell
  shell: which python python2 python3 | head -n1
  register: python_shell

- name: generate vm name
  shell: uuidgen
  register: vm_name_uuid

- name: set vm name
  copy:
    content: "docker-{{vm_name_uuid.stdout}}"
    dest: "{{data_dir}}/name"
