- name: add nfs utils
  apk:
    name: nfs-utils
  tags: provision

- name: start nfs daemon
  service:
    name: nfs
    enabled: True
    state: started
  tags: provision

- name: update exports file
  copy:
    dest: /etc/exports
    content: |
      /home/{{user_name}}/workspace *(rw,no_subtree_check,all_squash,insecure,async,anonuid={{user_uid}},anongid={{user_gid}})
  notify: reload nfs
