# file shares arent working atm, so just going to use this in the meantime.
- name: install rsync
  apk:
    name: rsync
  tags: provision

- name: set path
  set_fact:
    host_ssh_path: "/home/{{user_name}}/.host-ssh"

- name: copy keys
  synchronize:
    src: "{{hostvars['127.0.0.1'].ansible_env.HOME}}/.ssh/"
    dest: "{{host_ssh_path}}"
    private_key: ".data/key"
    delete: True
  delegate_to: localhost

- name: set permissions
  file:
    state: directory
    path: "{{host_ssh_path}}"
    owner: "{{user_name}}"
    group: "{{user_group_name}}"
    recurse: True
