
- name: add docker
  apk:
    name: docker
  register: add_docker
  tags: provision

- name: add docker-py
  pip:
    name: docker
    executable: /usr/bin/pip3

- name: ensure docker starts on reboot
  service:
    name: docker
    enabled: True
    state: started
  tags: provision

- name: add user to docker group
  user:
    name: "{{user_name}}"
    append: True
    groups: docker
