
- name: download alpine image
  get_url:
    url: https://github.com/AGhost-7/vbox-docker/releases/download/v19.03.29%2B6/vbox-docker.vmdk
    dest: "{{vm_data}}/vbox-docker.vmdk"
  register: vmdk_image
  tags: provision

- name: check if vdi exists
  stat:
    path: "{{vm_data}}/vbox-docker.vdi"
    get_checksum: False
  register: vdi_image
  tags: provision

- name: convert vmdk image to vdi format
  when: vmdk_image.changed or not vdi_image.stat.exists
  command: VBoxManage clonehd --format VDI "{{vm_data}}/vbox-docker.vmdk" "{{vm_data}}/vbox-docker.vdi"
  tags: provision
