
- name: set data directory location
  set_fact:
    data_dir: "{{playbook_dir}}/.data"

- name: create directory
  file:
    state: directory
    path: "{{data_dir}}"

- name: download ubuntu server image
  get_url:
    url: https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64-disk1.vmdk
    dest: "{{data_dir}}/ubuntu.vmdk"
  register: vmdk_image

- name: check if vdi exists
  stat:
    path: "{{data_dir}}/ubuntu.vdi"
  register: vdi_image

- name: convert vmdk image to vdi format
  when: vmdk_image.changed or not vdi_image.stat.exists
  command: VBoxManage clonehd --format VDI "{{data_dir}}/ubuntu.vmdk" "{{data_dir}}/ubuntu.vdi"

