- name: check if ssh key exists
  stat:
    path: "{{vm_data}}/key"
  register: ssh_key_stat
  tags: provision

- name: set key to use
  when: not ssh_key_stat.stat.exists
  set_fact:
    vm_ssh_key: 'packer/insecure-keys/id_rsa'

- name: set key to use
  when: ssh_key_stat.stat.exists
  set_fact:
    vm_ssh_key: "{{vm_data}}/key"

- name: set ssh options
  set_fact:
    ssh_options: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

- name: wait until ssh is available
  retries: 100
  delay: 2
  until: ssh_exit.rc == 0
  command: ssh {{ssh_options}} -p 2223 -i {{vm_ssh_key}} root@localhost exit
  register: ssh_exit

- name: create ssh key
  when: not ssh_key_stat.stat.exists
  command: ssh-keygen -t rsa -b 4096 -f "{{vm_data}}/key" -N ''

- name: replace ssh key with local key
  when: not ssh_key_stat.stat.exists
  command: scp {{ssh_options}} -P 2223 -i {{vm_ssh_key}} "{{vm_data}}/key.pub" root@localhost:/root/.ssh/authorized_keys
  tags: provision
