- name: list vms
  command: VBoxManage list vms
  register: vms

- name: remove vm
  when: vm_name in vms.stdout
  include_tasks: ./vm.yml

- name: remove files
  with_items:
    - key
    - key.pub
    - interface
    - name
  file:
    path: "{{vm_data}}/{{item}}"
    state: absent
